services:
  db:
    image: postgres:15
    container_name: mygoals
    restart: always
    env_file:
      - .env
    environment:
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
