services:
  db:
    image: postgres:15
    container_name: mygoals
    restart: always
    env_file:
      - .env
    environment:
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: mygoals-redis
    env_file:
      - .env
    environment:
      TZ: UTC
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  pg_data:
  redis_data:
