name: Run All Tests Pull Request

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      JWT_ALGORITHM: HS256

    steps:
      - name: python code checkout
        uses: actions/checkout@v3

      - name: Config Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
